# Generated by Django 5.2.7 on 2025-11-04 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(choices=[('DOG', 'Perro'), ('CAT', 'Gato'), ('BIRD', 'Ave'), ('RABBIT', 'Conejo'), ('FISH', 'Pez'), ('OTHER', 'Otro')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Macho'), ('FEMALE', 'Hembra')], max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Edad en años', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Peso en kg', null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/pets/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='store.customer')),
            ],
        ),
    ]
