# Generated by Django 5.2.7 on 2025-11-10 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile_alter_order_customer_alter_pet_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
