# Generated by Django 5.2.7 on 2025-11-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_date_shipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_shipped',
            new_name='shipped_date',
        ),
    ]
