# Generated by Django 5.2.7 on 2025-11-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_date_shipped_order_shipped_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='final_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
