# Generated by Django 4.2.7 on 2025-09-15 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0006_item_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_original', models.ImageField(upload_to='disenos/originales/')),
                ('imagen_formateada', models.ImageField(blank=True, null=True, upload_to='disenos/formateados/')),
                ('ubicacion_en_prenda', models.CharField(help_text='Ej: pecho, espalda, manga_izquierda, manga_derecha', max_length=100)),
                ('generado_por', models.CharField(choices=[('usuario', 'Usuario'), ('ia', 'IA')], default='usuario', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disenos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('camiseta', 'Camiseta'), ('camibuzo', 'Camibuzo'), ('hoodie', 'Hoodie')], max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('imagen_base', models.ImageField(upload_to='bases/')),
            ],
            options={
                'verbose_name': 'Plantilla base por color',
                'verbose_name_plural': 'Plantillas base por color',
                'unique_together': {('tipo', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ProductoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_en_prenda', models.CharField(help_text='pecho/espalda/manga_izquierda/manga_derecha', max_length=100)),
                ('color', models.CharField(default='negro', max_length=30)),
                ('imagen_visualizacion', models.ImageField(blank=True, null=True, upload_to='previews/')),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('diseno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalizaciones', to='personalizaciones.diseno')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalizaciones', to='items.item')),
            ],
            options={
                'verbose_name': 'Producto personalizado',
                'verbose_name_plural': 'Productos personalizados',
                'indexes': [models.Index(fields=['producto'], name='personaliza_product_298f79_idx'), models.Index(fields=['diseno'], name='personaliza_diseno__270baf_idx')],
            },
        ),
    ]
