# Generated by Django 4.2.7 on 2025-09-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillabase',
            name='tipo',
            field=models.CharField(choices=[('camiseta', 'Camiseta'), ('camibuso', 'Camibuso'), ('hoodie', 'Hoodie')], max_length=20),
        ),
    ]
