# Generated by Django 4.2.7 on 2025-09-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizaciones', '0002_alter_plantillabase_tipo'),
        ('personalizaciones', '0002_fix_camibuzo_spelling'),
    ]

    operations = [
    ]
