# Generated by Django 4.2.7 on 2025-09-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizaciones', '0002_fix_camibuzo_data'),
        ('personalizaciones', '0003_merge_20250915_0434'),
    ]

    operations = [
    ]
