# Generated by Django 4.2.7 on 2025-10-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizaciones', '0004_merge_0002_fix_camibuzo_data_0003_merge_20250915_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseno',
            name='posicion_x',
            field=models.FloatField(default=0.5, help_text='Posición X como porcentaje del ancho de la prenda (0.0 a 1.0)'),
        ),
        migrations.AddField(
            model_name='diseno',
            name='posicion_y',
            field=models.FloatField(default=0.35, help_text='Posición Y como porcentaje de la altura de la prenda (0.0 a 1.0)'),
        ),
        migrations.AddField(
            model_name='diseno',
            name='tamaño_imagen',
            field=models.FloatField(default=0.3, help_text='Tamaño de la imagen como porcentaje del ancho de la prenda (0.1 a 1.0)'),
        ),
    ]
