# Generated by Django 4.2.7 on 2023-11-25 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_item_discount_item_is_on_sale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("title",)},
        ),
    ]
