# Generated by Django 4.2.7 on 2023-11-25 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("items", "0003_alter_item_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.FloatField(default=0.0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="item",
            name="buyers",
        ),
        migrations.DeleteModel(
            name="Purchase",
        ),
        migrations.AddField(
            model_name="purchasereceipt",
            name="items",
            field=models.ManyToManyField(
                related_name="purchase_receipts", to="items.item"
            ),
        ),
    ]
