# Generated by Django 4.2.7 on 2025-09-13 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_purchasereceipt_remove_item_buyers_delete_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereceipt',
            name='items',
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to='items.purchasereceipt')),
            ],
        ),
    ]
