# Generated by Django 4.2.7 on 2025-09-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_purchasereceipt_items_purchaseditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
