# Generated by Django 4.2.7 on 2025-09-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0007_pedido_pedidoitem_pedido_productos"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="recibo_pdf",
            field=models.FileField(blank=True, null=True, upload_to="recibos/"),
        ),
    ]
