# Generated by Django 4.2.7 on 2025-09-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='imagen_diseno',
            field=models.ImageField(blank=True, null=True, upload_to='cart/designs/'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='M', max_length=10),
        ),
    ]
